apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  dataVolumeTemplates:
  - metadata:
      name: volume1
    spec:
      storage:
        resources:
          requests:
            storage: 5Gi
      source:
        registry:
          url: "docker://quay.io/kubevirtci/fedora-with-test-tooling:fc35-2208011009"
          pullMethod: node
  runStrategy: Always
  template:
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: root-volume
          interfaces:
          - masquerade: {}
            name: default
        resources:
          requests:
            memory: 4Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: volume1
        name: root-volume
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: volume1
# spec:
#   accessModes:
#   - ReadWriteMany
#   resources:
#     requests:
#       storage: "5368709120"
#   storageClassName: rook-ceph-block
#   volumeMode: Block
