apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volume1
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: "5368709120"
  storageClassName: rook-ceph-block
  volumeMode: Block
